[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd mobile-app-fresh && npm install"]

[phases.build]
cmds = ["cd mobile-app-fresh && npm run build"]

[start]
cmd = "cd mobile-app-fresh && npm run start:web:prod"
